kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.dags_volume_pvc }}
  labels:
    app: "legion-airflow-{{ .Values.enclave }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.storage.persistence_size | quote }}
  storageClassName: {{ .Values.storage.storageclass }}
