---
##################
# Install Legion 
##################

# Deploy airflow cluster to a specific enclave.
# Create aws resources if will be needed.

# NOTICE:
# You Must specify the next variables as extra vars (--extra-vars "XXXX=YYYY") 
# profile - unique cluster name
# legion_version - Legion version to deploy
# Optional arguments:
# docker_repo - rewrite docker registry endpoint
# enclave_name - enclave name

- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - "{{ lookup('env', 'PROFILES_PATH') or '../profiles' }}/{{ profile }}.yml"

  pre_tasks:
    - name: Download secrets from S3
      aws_s3:
        bucket: "{{ secrets_bucket }}"
        object: "vault/{{ profile }}"
        dest: "{{ secrets_file }}"
        mode: get

    - name: Include vars
      include_vars:
        file: "{{ secrets_file }}"

    - name: If enclave_name var will be passed than deploy airflow to this specific enclave
      set_fact: enclaves=[{{ enclave_name }}]
      when: enclave_name is defined and enclave_name | trim != ''

    - debug:
        msg: Deploy airflow to {{ enclaves }} enclave

  post_tasks:
    - name: Delete secrets file
      file:
        name: "{{ secrets_file }}"
        state: absent
  
  roles:
    - common
    - create_aws_resources

  tasks:
    - include_role:
        name: deploy
      with_items: "{{ enclaves }}"
      loop_control:
        loop_var: enclave
