{{- if not .Values.storage.use_specified_pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-dag-pvc"
  labels:
    app: "{{ .Release.Name }}-dag-pvc"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - {{ .Values.storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.persistenceSize | quote }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}
{{- end }}