---

- name: Create S3 storage for Airflow logs
  aws_s3:
    bucket: "{{ legion_data_s3_bucket }}"
    object: "/{{ airflow_s3_logs_path }}"
    mode: create

# Create IAM roles
- name: Generate Trust policy documents
  template:
    src: trust_policy.yaml.j2
    dest: "{{ tmp_dir }}/trust_policy.{{ cluster_name }}.yaml"

- name: Generate S3 access policy documents
  template:
    src: "enclave_s3_access_policy.yaml.j2"
    dest: "{{ tmp_dir }}/enclave_s3_access_policy.{{ enclave }}.{{ cluster_name }}.yaml"

- name: Create Airflow Enclave IAM roles
  iam:
    iam_type: role
    name: "{{ cluster_name }}-{{ enclave }}-airflow-role"
    trust_policy_filepath: "{{ tmp_dir }}/trust_policy.{{ cluster_name }}.yaml"
    state: present

- name: Attach Airflow S3 accesse policies to the roles
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-{{ enclave }}-airflow-role"
    policy_name: "{{ cluster_name }}-{{ enclave }}-s3-access-policy"
    policy_document: "{{ tmp_dir }}/enclave_s3_access_policy.{{ enclave }}.{{ cluster_name }}.yaml"
    state: present
