---
# Cluster specific data
env_name: legion-dev
env_type: dev
base_domain: epm.kharlamov.biz
cluster_name: "{{ profile }}"

# Common
secrets_bucket: "legion-cluster"
tmp_dir: /tmp
helm_local_src: false

# S3 storage 
legion_data_bucket_prefix: epm-legion-data
legion_data_s3_bucket: "{{ legion_data_bucket_prefix }}-{{ env_type }}-{{ enclave }}"
airflow_s3_logs_path: 'airflow-logs/'
airflow_s3_logs_url: "s3://{{ legion_data_s3_bucket }}/{{ airflow_s3_logs_path }}"

# EFS PVC for Dags
storageclass: efs
airflow_dags_dir: '/airflow-dags'
airflow_dags_pvc: legion-airflow-dags
airflow_expected_output: 'expected-data/'
airflow_pvc: 200m

# RDS database
airflow_rds_engine: "postgres"
airflow_rds_engine_version: "10.4"
root_domain: "{{ enclave }}.{{ base_domain }}"
domain_delimiter: "-"
namespace: "{{ enclave }}"
source_secret_name: "{{ base_domain }}-tls"
airflow_db_schema: "{{ enclave }}"
airflow_db_enclave_user: "{{ enclave }}"

# K8S POD parameters
airflow_worker_cpu_requests: "1500m"
airflow_worker_cpu_limits: "2000m"
airflow_worker_mem_requests: "1000Mi"
airflow_worker_mem_limits: "2500Mi"
