---
##################
# Install Legion 
##################

# Undeploy airflow from legion cluster

# NOTICE:
# You Must specify the next variables as extra vars (--extra-vars "XXXX=YYYY") 
# profile - unique cluster name
# Optional arguments:
# pypi_repo - rewrite pypi repo endpoint
# docker_repo - rewrite docker registry endpoint

- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - vars/common-vars.yaml

  pre_tasks:
    - name: Download secrets from S3
      aws_s3:
        bucket: "{{ secrets_bucket }}"
        object: "vault/airflow_secrets.yaml"
        dest: "airflow_secrets.yaml"
        mode: get

    - name: Include vars
      include_vars:
        file: "airflow_secrets.yaml"

    - name: If enclave_name var will be passed than deploy airflow to this specific enclave
      set_fact: enclaves=[{{ enclave_name }}]
      when: enclave_name is defined and enclave_name | trim != ''

  post_tasks:
    - name: Delete secrets file
      file:
        name: "airflow_secrets.yaml"
        state: absent

  roles:
    - commons

  tasks:
    - include_role:
        name: undeploy
      with_items: "{{ enclaves }}"
      loop_control:
        loop_var: enclave