---
- name: Configure kubectl using kops
  shell: "kops export kubecfg --name {{ cluster_name }} --state {{ state_store }}"

- name: Get legion chart status
  shell: helm --kube-context {{ cluster_name }} ls --all airflow-{{ enclave }}
  register: chart_status

- name: Delete airflow chart
  shell: helm --kube-context {{ cluster_name }} delete --purge airflow-{{ enclave }}
  when: chart_status.stdout.find("airflow") != -1

- name: WORKAROUND delete pods in phase terminating
  shell: kubectl --context {{ cluster_name }} --namespace {{ enclave }}  delete --grace-period=0 --force po $(kubectl --context {{ cluster_name }} --namespace {{ enclave }} get po -o wide | grep Terminating | awk '{ print $1 }') || true
