---

- name: Remove airflow chart
  shell: helm --kube-context {{ cluster_name }} delete --purge airflow-{{ enclave }}

- name: WORKAROUND delete pods in phase terminating
  shell: kubectl --context {{ cluster_name }} --namespace {{ enclave }}  delete --grace-period=0 --force po $(kubectl --context {{ cluster_name }} --namespace {{ enclave }} get po -o wide | grep Terminating | awk '{ print $1 }') || true
